In [1]:
import numpy as np
import time
# First Part
np.random.seed(24787)
a = np.random.randint(8, size=(3,4,4))
print("A = ",a)
print("Shape of A = ",np.shape(a))

# Locate value = 4
res = np.where(a == 4)
coordinates = list(zip(res[0], res[1], res[2]))
for i in coordinates:
    print("(depth, row, column) = ",i)

# Second Part
b = np.tile(a, (1, 2, 2))

# Third Part
c = np.sum(b, axis=0)
print("C = ",c)
print("Shape of C = ", np.shape(c))

A =  [[[2 6 4 1]
  [0 4 4 3]
  [6 6 1 2]
  [7 0 6 5]]

 [[1 3 3 7]
  [4 7 2 5]
  [0 4 6 7]
  [5 5 7 1]]

 [[7 2 4 5]
  [6 7 7 0]
  [6 2 0 4]
  [2 0 7 6]]]
Shape of A =  (3, 4, 4)
(depth, row, column) =  (0, 0, 2)
(depth, row, column) =  (0, 1, 1)
(depth, row, column) =  (0, 1, 2)
(depth, row, column) =  (1, 1, 0)
(depth, row, column) =  (1, 2, 1)
(depth, row, column) =  (2, 0, 2)
(depth, row, column) =  (2, 2, 3)
C =  [[10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]
 [10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]]
Shape of C =  (8, 8)


In [2]:
# Fourth Part
np.random.seed(24787)
a = np.random.randint(8, size=(1000,1000))
b = np.random.randint(8, size=(1000,1000))


c = np.zeros(a.shape)
def matmul(a,b):
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i,j] = np.dot(a[i,:], b[:,j].transpose())

z1 = time.time()
matmul(a,b)
print("Time elapsed = ", time.time() - z1)
print("Using row wise multiplicaiton: ",c)

z2 = time.time()
d = a@b
print("Using '@' operator:", d)
print("Time elapsed = ", time.time() - z2)

compare = c == d
result = compare.all()
  
print(result)

Time elapsed =  2.5482125282287598
Using row wise multiplicaiton:  [[12146. 12253. 12302. ... 12123. 12415. 12239.]
 [12251. 12131. 12180. ... 12691. 12396. 12497.]
 [11434. 11864. 12043. ... 12348. 11960. 12207.]
 ...
 [11774. 11945. 12276. ... 12339. 12178. 12059.]
 [11627. 12167. 12254. ... 11929. 11958. 12078.]
 [11560. 12145. 12077. ... 12210. 12124. 12031.]]
Using '@' operator: [[12146 12253 12302 ... 12123 12415 12239]
 [12251 12131 12180 ... 12691 12396 12497]
 [11434 11864 12043 ... 12348 11960 12207]
 ...
 [11774 11945 12276 ... 12339 12178 12059]
 [11627 12167 12254 ... 11929 11958 12078]
 [11560 12145 12077 ... 12210 12124 12031]]
Time elapsed =  0.637869119644165
True


In [3]:
'''
The inbuilt @ function is multiple times faster because of its vectorized form of execution. The for loops take a long time as compared
to its corresponding vectorized form.
'''

'\nThe inbuilt @ function is multiple times faster because of its vectorized form of execution. The for loops take a long time as compared\nto its corresponding vectorized form.\n'