In [5]:
#Problem 2 (E)

import numpy as np
def NUMPY_outer(X,Y):
    Ans = np.ones((len(X),len(Y)))
    for i in range(len(X)):
        for j in range(len(Y)):
            Ans[i,j] = X[i]*Y[j]
            
    print(Ans)      

np.random.seed(24787)
X = np.random.randint(-1000, 1000, size=(3000))
Y = np.random.randint(-1000, 1000, size=(3000))

print(np.outer(X,Y))
NUMPY_outer(X,Y)
'''
The numpy.outer() function is faster as it vectorizes the opoeration. 
The nested for loop gets slower due the number of iterations it has 
to execute. The vectorized form reduces the number of steps by a 
significant amount and hence, the numpy.outer() is executed faster. 
'''


[[ 288116  433466  322354 ...  234498  459306  323646]
 [ 214972  323422  240518 ...  174966  342702  241482]
 [-312200 -469700 -349300 ... -254100 -497700 -350700]
 ...
 [ 180184  271084  201596 ...  146652  287244  202404]
 [ -66454  -99979  -74351 ...  -54087 -105939  -74649]
 [ 203376  305976  227544 ...  165528  324216  228456]]
[[ 288116.  433466.  322354. ...  234498.  459306.  323646.]
 [ 214972.  323422.  240518. ...  174966.  342702.  241482.]
 [-312200. -469700. -349300. ... -254100. -497700. -350700.]
 ...
 [ 180184.  271084.  201596. ...  146652.  287244.  202404.]
 [ -66454.  -99979.  -74351. ...  -54087. -105939.  -74649.]
 [ 203376.  305976.  227544. ...  165528.  324216.  228456.]]
